### ISSUE TITLE
Fix view documentation about line statements

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/docs#87]
in docs, we should probably demonstrate what the elif block should look like with a condition…
<img width="343" alt="Screenshot 2019-08-04 at 18 56 32" src="https://user-images.githubusercontent.com/20172538/62427494-c74a7600-b6c1-11e9-9d4d-73013e58d188.png">

perhaps an easy first PR for someone

https://docs.masoniteproject.com/the-basics/views#if-statement

related: i find it a confusing message to show both jinja2 syntax and “@” syntax for templates

I think we should stick to one and promote it alone

related: i think it’s strange that the trailing : is optional and seldom demonstrated in docs. almost like it shouldn’t be demonstrated at all or it should be enforced by the parser.

e.g
```
@if expression:
# is the same as 
@if expression
```

https://docs.masoniteproject.com/the-basics/views#if-statement

**Comment by assertchris** [comment]
To make this easier, let's talk about the specifics of a PR we'd accept for this:
1. Change examples to favour `@if expression` over `{% if expression %}`, for all block types where appropriate
2. Change examples to show `@elif expression`
3. Change examples to omit optional trailing `:`; at the end of `@if expression:`, for all block types where appropriate

**PS** docs should still have an example of 1-line expressions, with the required Jinja2 syntax for them. We're not trying to blot out Jinja2 – we're trying to suggest a preferred style to reduce confusion.

Can I get thumbs up for these changes, or suggestions for alternatives?

Edit: I'm suggesting the block syntax because it's closer to [Blade](https://laravel.com/docs/5.8/blade) and [Edge](https://edge.adonisjs.com/docs/getting-started).

**Comment by raakesh** [comment]
Is it really required to have two kinds of syntax for all examples ?

Why not have only one of it and stick to it...

Edit: 
New users will be confused by two types of syntax in the documentation.

**Comment by assertchris** [comment]
@raakesh That's exactly the problem this issue is aiming to solve.

**Comment by tthebst** [comment]
Hi, I'm trying to update the docs. Does this @ notation also work with for loops and the block statements or should it only be used for if expressions?

**Comment by josephmancuso** [comment]
it works for `for` loops and i'm 98% sure it works for blocks too

**Comment by tthebst** [comment]
So should I update the for and block docs as well? Did I understand correctly that I should include a jinja and a line statement example.

**Comment by josephmancuso** [comment]
yes sorry that was cryptic. Yes it works for if statements, for loops and jinja blocks

**Comment by tthebst** [comment]
What do you think of the pull request?

**Comment by josephmancuso** [comment]
I’ll take a look in a bit. Been working on a project lately so didn’t get the chance yet
